name: Build and Dockerize

on:
  release:
    types: [ published ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.13' 

        - name: Install Python dependencies
          run: pip install -r requirements.txt

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '23'

        - name: Install NPM dependencies
          run: npm install

        - name: Build static web resources
          run: npm run build-css

        - name: Lint
          run: ruff check

        - name: Test
          run: python -m pytest . --cov=app

        - name: Coveralls GitHub Action
          uses: coverallsapp/github-action@v2.3.4

        - name: Extract release version
          run: |
            VERSION=${GITHUB_REF_NAME#v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Log in to GHCR
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3.3.0

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.8.0
        
        - name: Build image and push
          uses: docker/build-push-action@v6.12.0
          with:
            platforms: linux/amd64,linux/arm64
            tags: ghcr.io/mattgogerly/monzo-credit-card-pot-sync:${{ env.VERSION }}
            push: true